export const names = new Map<string, string>([
  ["\x1b", "ESC"],
  ["\r", "ENTER"],
  ["\t", "TAB"],
  ["\x7f", "BACKSPACE"],
  ["2~", "INSERT"],
  ["3~", "DELETE"],
  ["D", "LEFT"],
  ["1D", "LEFT"],
  ["C", "RIGHT"],
  ["1C", "RIGHT"],
  ["A", "UP"],
  ["1A", "UP"],
  ["B", "DOWN"],
  ["1B", "DOWN"],
  ["5~", "PAGE_UP"],
  ["6~", "PAGE_DOWN"],
  ["H", "HOME"],
  ["1H", "HOME"],
  ["7~", "HOME"],
  ["F", "END"],
  ["1F", "END"],
  ["8~", "END"],
]);
